version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: backend-challenge-julian:latest
        container_name: backend-challenge-julian
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        networks:
            - mynet
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: backend-challenge-julian-mysql
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: products
            MYSQL_USER: julian
            MYSQL_PASSWORD: test
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - mynet

networks:
    mynet:

volumes:
    dbdata:

